### ISSUE TITLE
please add me as a collaborator in this repo

### ISSUE THREAD

**Issue by chessai** [andrewthad/unpacked-maybe-numeric#1]
i was just thinking about making this the other day

**Comment by andrewthad** [comment]
In that case, you beat me to it. I've only been think about it since this morning. Types I was considering:

- `Word` (partially implemented)
- `Int`
- `Double`
- `Complex Double`

Sub-machine-word-size numbers deserve a slightly different implementation. For example, it doesn't really make sense to do `Int8` as `(# (# #) | Int# #)` because you really could just do it as `Int#`. This may change if the proposal for adding `Int8#` and friends is accepted.

**Comment by chessai** [comment]
Wait, why wouldn't sub-machine-word-size numbers make sense to do as `(# (# #) | Int# #)`? Are you saying because it'll take up too much space? How could you do it as just `Int#`? I'm aware of that proposal, but unsure how it affects this _currently_.

**Comment by chessai** [comment]
also this is unrelated but your module names are getting a little long lately

**Comment by andrewthad** [comment]
Yes, it would take up more space that needed. The space requirements of `(# (# #) | Int# #)` are one machine word plus one byte. However, for represented a `Maybe Int8`, you could just use the one machine word for `Int#` and use one of the out-of-bounds values as a surrogate for `Nothing`. If the sub-machine-word-size-primitives proposal is implemented, we could write `(# (# #) | Int8# #)`, which would only take two bytes when unpacked into a data constructor.

**Comment by chessai** [comment]
OK, that makes sense

**Comment by chessai** [comment]
If the proposal is accepted would it make sense to keep this as-is and just
switch stuff out with the new GHC, or should I go ahead and fix it for now
to use Int#

**Comment by andrewthad** [comment]
I would say to go ahead and do it as an unboxed sum  in anticipation of the proposal’s implementation.  It will still require some minor changes after the proposal is implemented,  but at least it won’t have to be totally rewritten.
